import { Initiatives } from "./types";

export const initiativesList: Initiatives[] = [
  {
    id: "65d606d6b0ed69c2c345c86d",
    name: "Testing",
    author: "Camilo",
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    mnemonic: "TPaP",
    neccesity: "Manejo eficiente de usuarios",
    status: "created",
    managers: ["Manager 1"],
    created: "2024-03-01T16:30:08.099Z",
  },
  {
    id: "65e0d910779c6bdca566731c",
    name: "Augmented",
    author: "Luis Carlos",
    description: "Iniciativa para DOJO",
    objetive: "Aplicacion para migrar data",
    mnemonic: "TPaP",
    neccesity: "Manejo eficiente de usuarios",
    status: "draft",
    managers: ["Pedro", "Carlos Oviedo"],
    created: "2024-03-01T16:30:24.964Z",
  },
  {
    id: "65e0d940779c6bdca566731d",
    name: "Augmented 2",
    author: "Luis Carlos Sarmiento",
    description: "Iniciativa para DOJO V2",
    objetive: "Aplicacion para migrar servicios",
    mnemonic: "DART",
    neccesity: "Manejo eficiente de microservicios",
    status: "approved",
    managers: ["Andres Saldarriega", "Carlos"],
    created: "2024-03-01T16:30:36.940Z",
  },
];

export const initiativesData = [
  {
    id: 1,
    name: "Project-Augmented TPaP",
    author: "John Doe",
    mnemonic: "PTAP",
    status: "draft",
    managers: ["Manager 1"],
    created: "10-03-2023",
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 2,
    name: "MagnifAI",
    author: "Jane Smith",
    mnemonic: "MAGAI",
    status: "draft",
    created: "15-03-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 3,
    name: "Proyecto Globery",
    author: "John Doe",
    mnemonic: "GLORY",
    status: "approved",
    created: "20-03-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 4,
    name: "Proyecto Exogames",
    author: "Sarah Thompson",
    mnemonic: "EXOGM",
    status: "draft",
    created: "25-03-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 5,
    name: "Initiative ABC",
    author: "David Williams",
    mnemonic: "INITA",
    status: "rejected",
    created: "30-03-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 6,
    name: "Initiative XYZ",
    author: "Emily Davis",
    mnemonic: "INITX",
    status: "approved",
    created: "05-04-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 7,
    name: "New Project NP",
    author: "Steven Wilson",
    mnemonic: "NPROJ",
    status: "draft",
    created: "10-04-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 8,
    name: "Innovative Idea II",
    author: "Amanda Taylor",
    mnemonic: "INOVD",
    status: "rejected",
    created: "15-04-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 9,
    name: "Creative Solution CS",
    author: "Matthew Anderson",
    mnemonic: "CRSOL",
    status: "approved",
    created: "20-04-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
  {
    id: 10,
    name: "Unique Concept UC",
    author: "Olivia Martinez",
    mnemonic: "UNCON",
    status: "draft",
    created: "25-04-2023",
    managers: ["Manager 1"],
    description: "Iniciativa de prueba",
    objetive: "Crear aplicación que adminitra usuarios",
    neccesity: "Manejo eficiente de usuarios",
  },
];
